### ISSUE TITLE
Сделать серверную часть программы.

### ISSUE THREAD

**Issue by chebupelka10** [FozerG/YandexMusicRPC#1]
Я не Столкнулся с проблемой: бла, бла, бла. 
Что я сделал что бы получить эту проблему: падумал башкой.

OS: ubuntu (чистая, не сборка)

Привет! Давно юзаю твою прогу на яндекс музыку. Было бы прикольно если бы можно было бы прогу на сервер поставить.

Идея такая - если я запущу прогу на сервере то оно будет показыватся в RPC. Если програмной(не обязательно иметь открытую ямузыку и прогу на пк) части нету, то почему и не сделать серверный билд? И вход будет через просто получение токена. 

ну или просто дай туториал если такое уже есть.

спасибо

**Comment by FozerG** [comment]
Привет! Теоретически, это можно реализовать, но если речь идет именно о статусе в Discord, потребуется продумать механизм работы.

Дело в том, что в текущей реализации Discord должен быть установлен и запущен на устройстве, а это невозможно на сервере. Чтобы обойти это ограничение, придется работать через API Discord. Но такой подход может быть довольно сложным и не всегда практичным. 

Если речь идет о графической версии Ubuntu, то её можно использовать в качестве сервера если скрипт будет работать. В перспективе я планирую добавить возможность запуска скрипта на различных операционных системах. Это также может быть реализовано любым энтузиастом, что, вероятно, произойдет быстрее.

**Comment by FozerG** [comment]
Кстати, я не пробовал запускать программу через Wine, но это может быть отличной отправной точкой.

**Comment by chebupelka10** [comment]
wine много потребляет, можно конечно бутылку с ДС и твоей прогой. а на сервере можно впринципе гном установить.

**Comment by FozerG** [comment]
Да, бутылка с дискордом и скриптом должна работать в теории, но, скорее всего, не все будет идеально работать. В любом случае нужно понять, что это очень специфическая задача, которая отличается от первоначальных целей, ради которых я создал скрипт :)

**Comment by chebupelka10** [comment]
это то понятно, я подумаю как можно это сделать и потом напишу сюда.

**Comment by chebupelka10** [comment]
я прочитал в интернете, в этом особо ничего нету сложного как я понял. надо получить токен для входа именно в дискорд и яндекс музыки, который можно получить либо стандартным способом через ссылку или так:

client = Client.from_credentials('емаил', 'пароль')

И через либу requests кинуть json запрос на ссылку "https://discord.com/api/v10/users/@me/settings"
Примерно можно сделать так
    headers = {
        "Authorization": token,
        "Content-Type": "application/json",
    }
    
   и вот так будет выглядеть сама строка отправки
   response = requests.patch(DISCORD_API_URL, json=payload, headers=headers)
