### ISSUE TITLE
статус консоли

### ISSUE THREAD

**Issue by subwaylover-spb** [FozerG/YandexMusicRPC#2]
здраствуйте появилась следущяя проблема
после установки программы моим другом началась странное отображение трека
в яндекс музыке(бета прилож) всё показывает нормально но в консоли программы висит трек который не соответсвует  играющему (скрин прикладываю)
[Image](https://github.com/user-attachments/assets/7b4032de-a7b4-4d3f-8c87-eb4ceb9c04f6)

хотел бы узнать как это починить
спасибо за ответ

**Comment by subwaylover-spb** [comment]
от себя добавлю
у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера
![image](https://github.com/user-attachments/assets/d5cf060d-c0d0-4e1f-8f83-c870359f7bea)

**Comment by subwaylover-spb** [comment]
треки показывает но потом ломается

**Comment by FozerG** [comment]
Для бета версии это ожидаемое поведение, я думаю. Трек может зависнуть, если, например, переключать музыку между компьютером и телефоном в реальном времени. Чтобы избежать зависания трека, рекомендуется закрывать приложение Яндекс.Музыки на устройствах, которые в данный момент не используются.

**Comment by subwaylover-spb** [comment]
> Для бета версии это ожидаемое поведение, я думаю. Трек может зависнуть, если, например, переключать музыку между компьютером и телефоном в реальном времени. Чтобы избежать зависания трека, рекомендуется закрывать приложение Яндекс.Музыки на устройствах, которые в данный момент не используются.

скрипт был установлен недавно

**Comment by subwaylover-spb** [comment]
у меня все работает правильно 
но у друга при использовании приложения на пк то начинается у друга такая херь

**Comment by FozerG** [comment]
> > Для бета версии это ожидаемое поведение, я думаю. Трек может зависнуть, если, например, переключать музыку между компьютером и телефоном в реальном времени. Чтобы избежать зависания трека, рекомендуется закрывать приложение Яндекс.Музыки на устройствах, которые в данный момент не используются.
> 
> скрипт был установлен недавно

Так и он вышел вчера :) Это к чему?

**Comment by subwaylover-spb** [comment]
> > > Для бета версии это ожидаемое поведение, я думаю. Трек может зависнуть, если, например, переключать музыку между компьютером и телефоном в реальном времени. Чтобы избежать зависания трека, рекомендуется закрывать приложение Яндекс.Музыки на устройствах, которые в данный момент не используются.
> > 
> > 
> > скрипт был установлен недавно
> 
> Так и он вышел вчера :) Это к чему?

извеняюсь не правильно написал

**Comment by subwaylover-spb** [comment]
> здраствуйте появилась следущяя проблема после установки программы моим другом началась странное отображение трека в яндекс музыке(бета прилож) всё показывает нормально но в консоли программы висит трек который не соответсвует играющему (скрин прикладываю) [Image](https://github.com/user-attachments/assets/7b4032de-a7b4-4d3f-8c87-eb4ceb9c04f6)
> 
> хотел бы узнать как это починить спасибо за ответ

попробую чуть правильнее описать

программа установлена минут 30 назад, посоветовал другу
он её запустил она установилась минут 2 работала нормально и потом зависла на одном треке, слушал он только на пк телефон не открывал

**Comment by FozerG** [comment]
Повторяю еще раз: закрываем приложение Яндекс.Браузера на всех устройствах (как на телефонах, так и в браузере) и пользуемся одним приложением, например, новым приложением для Windows. В таком случае должно работать более стабильно. На данный момент у меня все работает именно так. Если возникли проблемы, всегда можно вернуться к [этой версии которая не получает данные с серверов](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.4.1)

**Comment by subwaylover-spb** [comment]
> Повторяю еще раз: закрываем приложение Яндекс.Музыки на всех устройствах (как на телефонах, так и в браузере) и пользуемся одним приложением, например, новым приложением для Windows. В таком случае должно работать более стабильно. На данный момент у меня все работает именно так. Если возникли проблемы, всегда можно вернуться к [этой версии которая не получает данные с серверов](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.4.1)

понял, сейчас попробуем кое что сделать если не получится но откатим до старой версии

**Comment by FozerG** [comment]
> > здраствуйте появилась следущяя проблема после установки программы моим другом началась странное отображение трека в яндекс музыке(бета прилож) всё показывает нормально но в консоли программы висит трек который не соответсвует играющему (скрин прикладываю) [Image](https://github.com/user-attachments/assets/7b4032de-a7b4-4d3f-8c87-eb4ceb9c04f6)
> > хотел бы узнать как это починить спасибо за ответ
> 
> попробую чуть правильнее описать
> 
> программа установлена минут 30 назад, посоветовал другу он её запустил она установилась минут 2 работала нормально и потом зависла на одном треке, слушал он только на пк телефон не открывал

Можно попробовать перезапустить все: как сам скрипт, так и приложение Яндекс.Музыки. Как вариант...

**Comment by subwaylover-spb** [comment]
> > > здраствуйте появилась следущяя проблема после установки программы моим другом началась странное отображение трека в яндекс музыке(бета прилож) всё показывает нормально но в консоли программы висит трек который не соответсвует играющему (скрин прикладываю) [Image](https://github.com/user-attachments/assets/7b4032de-a7b4-4d3f-8c87-eb4ceb9c04f6)
> > > хотел бы узнать как это починить спасибо за ответ
> > 
> > 
> > попробую чуть правильнее описать
> > программа установлена минут 30 назад, посоветовал другу он её запустил она установилась минут 2 работала нормально и потом зависла на одном треке, слушал он только на пк телефон не открывал
> 
> Можно попробовать перезапустить все: как сам скрипт, так и приложение Яндекс.Музыки. Как вариант...

сейчас попробуем и отпишу с результатом

**Comment by subwaylover-spb** [comment]
есть ли кстати какой нибуть дс сервер для связи?

**Comment by FozerG** [comment]
> есть ли кстати какой нибуть дс сервер для связи?

Неа :(

**Comment by subwaylover-spb** [comment]
> Версию приложения Яндекс Музыки тоже желательно проверить

говорит что последняя бетка установлена

**Comment by FozerG** [comment]
> > Версию приложения Яндекс Музыки тоже желательно проверить
> 
> говорит что последняя бетка установлена

5.29.3? 
![image](https://github.com/user-attachments/assets/717fe0bc-0e5c-44fb-9d4f-bee4ccd64f0d)

**Comment by subwaylover-spb** [comment]
> > > Версию приложения Яндекс Музыки тоже желательно проверить
> > 
> > 
> > говорит что последняя бетка установлена
> 
> 5.29.3? ![image](https://private-user-images.githubusercontent.com/78788357/389294731-717fe0bc-0e5c-44fb-9d4f-bee4ccd64f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MTcsIm5iZiI6MTczMjQ3MTExNywicGF0aCI6Ii83ODc4ODM1Ny8zODkyOTQ3MzEtNzE3ZmUwYmMtMGU1Yy00NGZiLTlkNGYtYmVlNGNjZDY0ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE3NTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZjllZGZlNjRlOTUwOWViY2FhMDU2ZDMzMzc4MjcxYWE5NWRhZDA0YjMzYWYxYTJmZjI4ZWVhZDlkMjFmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GgfYANDWmbAgZpZCmTGHiOCwp1uvkMQ73vOHpXnbm3k)

yep

**Comment by subwaylover-spb** [comment]
телефон регает нормально но вот пк версию нет
друг пробует переустановить прогу

**Comment by subwaylover-spb** [comment]
телефон регает но пк версию нет

**Comment by subwaylover-spb** [comment]
перезапуск не помогает

**Comment by FozerG** [comment]
А через браузер с новым дизайном?

**Comment by subwaylover-spb** [comment]
> А через браузер с новым дизайном?

регает

**Comment by subwaylover-spb** [comment]
кажись поняли в чем проблема

**Comment by subwaylover-spb** [comment]
у этого придурка был выход с аккаунта в бета приложении

**Comment by subwaylover-spb** [comment]
простите что заняли ваше время

**Comment by FozerG** [comment]
Рад что решилось :)

**Comment by subwaylover-spb** [comment]
> от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)

касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось

**Comment by FozerG** [comment]
> > от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)
> 
> касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось

Ты пробовал это на Android?

**Comment by subwaylover-spb** [comment]
> > > от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)
> > 
> > 
> > касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось
> 
> Ты пробовал это на Android?

да

**Comment by subwaylover-spb** [comment]
> > > > от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)
> > > 
> > > 
> > > касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось
> > 
> > 
> > Ты пробовал это на Android?
> 
> да

вышел из дома и только придя домой увидел вот такое в консоли

**Comment by FozerG** [comment]
> > > > от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)
> > > 
> > > 
> > > касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось
> > 
> > 
> > Ты пробовал это на Android?
> 
> да

А вообще работает с телефона хоть какое то время?

**Comment by subwaylover-spb** [comment]
> > > > > от себя добавлю у себя заметил что приложение видит проигрование с телефона но вылезает ошибка данного характера ![image](https://private-user-images.githubusercontent.com/189545524/389293401-d5cf060d-c0d0-4e1f-8f83-c870359f7bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NzE0MDIsIm5iZiI6MTczMjQ3MTEwMiwicGF0aCI6Ii8xODk1NDU1MjQvMzg5MjkzNDAxLWQ1Y2YwNjBkLWMwZDAtNGUxZi04ZjgzLWM4NzAzNTlmN2JlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNzU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjMyNDUxNjI5ODFkMDA1YzE2NjE3YTRlMjczZWVjN2FkZDUyYzk3MWE5MmE5OGQzMjNiNTVhZGUzN2UzMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bh4BzIWDYPRB_gRDWoVZGSGcPap5yw0lIXkvUQHFA1o)
> > > > 
> > > > 
> > > > касаемо этого, если я ухожу из дома то мне нужно закрывать приложенеие на пк что бы все праивльно показывалось
> > > 
> > > 
> > > Ты пробовал это на Android?
> > 
> > 
> > да
> 
> А вообще работает с телефона хоть какое то время?

2-5 мин +-

**Comment by subwaylover-spb** [comment]
тут видео отправлять можно?

**Comment by FozerG** [comment]
Можешь сказать версию приложение в настройках приложения на телефоне? Потому что на Android я не смог протестировать

**Comment by FozerG** [comment]
> тут видео отправлять можно?

Только если на ютуб перезаливать

**Comment by subwaylover-spb** [comment]
версия 2024.11.2 #73gpr

**Comment by FozerG** [comment]
Спасибо, буду тестировать. По поводу ошибки - у меня такое было когда было короткое отключение интернета. Сложно сказать что можно сейчас сделать, буду работать над этим. В данный момент слушаю музыку с телефона и ошибок не вижу

**Comment by subwaylover-spb** [comment]
> > Спасибо, буду тестировать. По поводу ошибки - у меня такое было когда было короткое отключение интернета. Сложно сказать что можно сейчас сделать, буду работать над этим. В данный момент слушаю музыку с телефона и ошибок не вижу
> 
> попробовал эмулировать пропажу интернета якобы зашел в лифт, без результата

попробую запустить чуть позже и выйти наулицу

**Comment by subwaylover-spb** [comment]
> > > Спасибо, буду тестировать. По поводу ошибки - у меня такое было когда было короткое отключение интернета. Сложно сказать что можно сейчас сделать, буду работать над этим. В данный момент слушаю музыку с телефона и ошибок не вижу
> > 
> > 
> > попробовал эмулировать пропажу интернета якобы зашел в лифт, без результата
> 
> Я про интернет на компьютере с запущеным скриптом :)
 
проверил, да дейсвительно смог эмулировать ошибку путем пропажи интернета на машине где запущен скрипт

**Comment by subwaylover-spb** [comment]
вообщем спасибо за помощь и за такой качественно сделанный скрипт, видел ещё скрипт но проработан тот плохо и работал только с я.музыкой только с майк.стора

**Comment by subwaylover-spb** [comment]
![image](https://github.com/user-attachments/assets/45a57762-b8be-4da6-aa78-be53bd09998b)
ничего не делалЮ просто ушел просле теста а тут такое
кабель эзернет цел

**Comment by subwaylover-spb** [comment]
думаю прога просто не смогла после этого получить данные

**Comment by FozerG** [comment]
Сейчас могу лишь предложить ждать версию 0.2, и я попробую в ней исправить это. В течении пары дней я найду время

**Comment by subwaylover-spb** [comment]
про обновление так же можно будет узнать в консоле приложения?

**Comment by FozerG** [comment]
> про обновление так же можно будет узнать в консоле приложения?

Да, сообщение вылезет при запуске (должно ха-ха)

**Comment by subwaylover-spb** [comment]
> > про обновление так же можно будет узнать в консоле приложения?
> 
> Да, сообщение вылезет при запуске (должно ха-ха)

ну так и произашло
