### ISSUE TITLE
предложение

### ISSUE THREAD

**Issue by subwaylover-spb** [FozerG/YandexMusicRPC#3]
может попробовать сделать что бы установщик новой версии удалял старую и ставил новую, я незнаю можно ли это реализовать
если да то трудноли?

**Comment by subwaylover-spb** [comment]
так и должно быть?
![image](https://github.com/user-attachments/assets/4f7b18e5-aee0-4132-87c6-84604a18f140)

**Comment by FozerG** [comment]
> так и должно быть? ![image](https://private-user-images.githubusercontent.com/189545524/390103204-4f7b18e5-aee0-4132-87c6-84604a18f140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzI2MDgsIm5iZiI6MTczMjY3MjMwOCwicGF0aCI6Ii8xODk1NDU1MjQvMzkwMTAzMjA0LTRmN2IxOGU1LWFlZTAtNDEzMi04N2M2LTg0NjA0YTE4ZjE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMTUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzM4MGMxYmZlNTM5NzE5NDU1NGVmMWZhZmRhMGU4YmViZDQ5MTM5OTgxYjVhMDAxMTcwYTNjNDA1MzEyNmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wkBzOK043J-Swrsnm0nx1AIZM6rQ4EXIE1dvgqR4AYk)

Что именно интересует? Ошибка красным? Вполне нормально, может случаться но через пару секунд все должно восстановиться

**Comment by FozerG** [comment]
> может попробовать сделать что бы установщик новой версии удалял старую и ставил новую, я незнаю можно ли это реализовать если да то трудноли?

Установщик и сейчас делает установку поверх старой

**Comment by subwaylover-spb** [comment]
> > может попробовать сделать что бы установщик новой версии удалял старую и ставил новую, я незнаю можно ли это реализовать если да то трудноли?
> 
> Установщик и сейчас делает установку поверх старой

получается нет необходимости удалять старое и ставить новое

**Comment by FozerG** [comment]
> > > может попробовать сделать что бы установщик новой версии удалял старую и ставил новую, я незнаю можно ли это реализовать если да то трудноли?
> > 
> > 
> > Установщик и сейчас делает установку поверх старой
> 
> получается нет необходимости удалять старое и ставить новое

Верно :)
