### ISSUE TITLE
вечная пауза и подхват старого трека

### ISSUE THREAD

**Issue by llimonix** [FozerG/YandexMusicRPC#4]
уже известная проблема ynison , он не понимает когда стоит пауза, а когда ее нет. Из за этого ложное срабатывание, что в данный момент песня на паузе, хотя на деле это не так

![image](https://github.com/user-attachments/assets/435efc0a-c48b-48d3-a097-3a877fb75896)

С новым дизайном в версии в браузере все стабильно

**Comment by FozerG** [comment]
Проблема не в вечной паузе, а в том, что новые треки не передаются в Ynison. Т ы используешь приложение версии 5.29.3? Пробовал ли перезапускать приложение Яндекс Музыки?

**Comment by llimonix** [comment]
> Проблема не в вечной паузе, а в том, что новые треки не передаются в Ynison. Т ы используешь приложение версии 5.29.3? Пробовал ли перезапускать приложение Яндекс Музыки?

- Да
- Да

**Comment by FozerG** [comment]
Если в браузере все нормально, значит проблема не на стороне скрипта, а на стороне яндекса. Всё таки ynison только вышел в свет, нужно дать ему время :)

**Comment by llimonix** [comment]
Я разобрался в проблеме, у меня работало Яндекс Музыка, но она не засчитывала что я авторизован в ее десктоп приложение, хотя всю информацию обо мне выводила, я переавторизовался в приложение и все завелось. Спасибо за ваши старания и эту программу

**Comment by FozerG** [comment]
> Я разобрался в проблеме, у меня работало Яндекс Музыка, но она не засчитывала что я авторизован в ее десктоп приложение, хотя всю информацию обо мне выводила, я переавторизовался в приложение и все завелось. Спасибо за ваши старания и эту программу
> 
> Так же нужно пофиксить отображение девайса с которого играет, так как сейчас всегда Unknown

Отображение девайса работает только с мобильных устройств
