### ISSUE TITLE
on/off pause in track

### ISSUE THREAD

**Issue by subwaylover-spb** [FozerG/YandexMusicRPC#7]
проблемы не обходят меня стороной
сейчас при новой версии бета приложения я,музыка постоянная постановка на паузу

версия яндекс музыка (бета) 5.31.2

версия скрипта: 0,2,2

видео запищу, но чуть погодя так как нет нужной проги для этого

**Comment by subwaylover-spb** [comment]
файл слишком большой так что выкладываю сюда ссылку на ютуб

https://youtu.be/poK3W-Ghnbc

**Comment by FozerG** [comment]
В прошлом тикете тебе объяснил же. [#6](https://github.com/FozerG/YandexMusicRPC/issues/6#issuecomment-2515795493)

**Comment by subwaylover-spb** [comment]
прости невнимательный я чёт стал
